#!/usr/bin/env python3
"""Resolve NiFi + Ollama at startup.

If a live NiFi or Ollama instance is already reachable (Docker container or
host process), reuse it. Otherwise allocate a free host port and create a
new compose service on that port.
"""

from __future__ import annotations

import argparse
import json
import socket
import ssl
import subprocess
import sys
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path
from typing import Any

# High 27xxx band — away from 4200 / 8080 / 5555 / 11434 / 8555 used by local tools.
PREFERRED = {
    "NIFI_HOST_PORT": 27111,       # HTTP proxy — this is the URL you open
    "NIFI_TLS_HOST_PORT": 27113,   # raw NiFi HTTPS, only when we create a container
    "NIFI_PROXY_HOST_PORT": 27111,
    "MCP_HOST_PORT": 27115,
    "OLLAMA_HOST_PORT": 27134,
    "ORCHESTRATOR_HOST_PORT": 27110,
    "UI_HOST_PORT": 27120,
}

NIFI_PROBE_PORTS = (27111, 8555, 8443, 8080, 8081, 9443, 18443)
OLLAMA_PROBE_PORTS = (27134, 11434, 11435, 11436)
SPAN = 80

SSL_CTX = ssl._create_unverified_context()

# Old .env.example address. Never treat it as a live NiFi unless it probes OK.
STALE_EXAMPLE_HOSTS = {"172.25.125.123"}
BLOCKED_HOST_PORTS = {5000, 2375, 2376, 3306, 5432, 6379, 9042, 27017}
NIFI_LIKE_CONTAINER_PORTS = {8443, 8080, 8081, 9443, 18443, 8555, 443, 8444}


def port_bound(port: int) -> bool:
    for family, host in ((socket.AF_INET, "0.0.0.0"), (socket.AF_INET6, "::")):
        try:
            with socket.socket(family, socket.SOCK_STREAM) as s:
                s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
                if family == socket.AF_INET6:
                    try:
                        s.setsockopt(socket.IPPROTO_IPV6, socket.IPV6_V6ONLY, 1)
                    except OSError:
                        pass
                s.bind((host, port))
        except OSError:
            return True
    return False


def localhost_listening(port: int) -> bool:
    for family, host in ((socket.AF_INET, "127.0.0.1"), (socket.AF_INET6, "::1")):
        try:
            with socket.socket(family, socket.SOCK_STREAM) as s:
                s.settimeout(0.2)
                if s.connect_ex((host, port)) == 0:
                    return True
        except OSError:
            continue
    return False


def next_free(preferred: int, used: set[int]) -> int:
    for port in range(preferred, preferred + SPAN):
        if port in used:
            continue
        if port_bound(port) or localhost_listening(port):
            continue
        return port
    raise RuntimeError(f"No free TCP port in {preferred}..{preferred + SPAN - 1}")


def http_json(url: str, timeout: float = 1.2) -> Any | None:
    try:
        req = urllib.request.Request(url, method="GET")
        with urllib.request.urlopen(req, timeout=timeout, context=SSL_CTX) as resp:
            raw = resp.read(8000).decode("utf-8", "ignore")
        return json.loads(raw)
    except Exception:
        return None


def http_meta(url: str, timeout: float = 1.2) -> tuple[int, str]:
    try:
        req = urllib.request.Request(url, method="GET")
        with urllib.request.urlopen(req, timeout=timeout, context=SSL_CTX) as resp:
            body = resp.read(4000).decode("utf-8", "ignore")
            return int(getattr(resp, "status", 200)), body
    except urllib.error.HTTPError as e:
        try:
            body = e.read(4000).decode("utf-8", "ignore")
        except Exception:
            body = ""
        return int(e.code), body
    except Exception:
        return 0, ""


def parse_env(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, val = line.split("=", 1)
        values[key.strip()] = val.strip()
    return values


def write_env(path: Path, updates: dict[str, str]) -> None:
    keys_written: set[str] = set()
    lines: list[str] = []
    existing = path.read_text(encoding="utf-8").splitlines() if path.exists() else []
    if not existing:
        lines.append("# Generated by scripts/allocate_ports.py")
        lines.append("# Existing NiFi/Ollama are reused; otherwise a new instance is created.")
        lines.append("")

    for raw in existing:
        if not raw.strip() or raw.strip().startswith("#") or "=" not in raw:
            lines.append(raw)
            continue
        key = raw.split("=", 1)[0].strip()
        if key in updates:
            lines.append(f"{key}={updates[key]}")
            keys_written.add(key)
        else:
            lines.append(raw)

    for key, val in updates.items():
        if key not in keys_written:
            lines.append(f"{key}={val}")

    path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def docker_ps() -> list[dict[str, str]]:
    try:
        proc = subprocess.run(
            [
                "docker",
                "ps",
                "--format",
                "{{.ID}}\t{{.Names}}\t{{.Image}}\t{{.Ports}}\t{{.Label \"com.docker.compose.service\"}}",
            ],
            capture_output=True,
            text=True,
            timeout=8,
        )
    except Exception:
        return []
    if proc.returncode != 0:
        return []
    rows = []
    for line in proc.stdout.splitlines():
        parts = line.split("\t")
        if len(parts) < 4:
            continue
        rows.append(
            {
                "id": parts[0],
                "name": parts[1],
                "image": parts[2],
                "ports": parts[3],
                "service": parts[4] if len(parts) > 4 else "",
            }
        )
    return rows


def published_ports(port_field: str) -> list[tuple[int, int]]:
    """Parse docker ps Ports column → [(host_port, container_port), ...]."""
    found: list[tuple[int, int]] = []
    # 0.0.0.0:8555->8443/tcp, [::]:8555->8443/tcp
    for chunk in port_field.split(","):
        chunk = chunk.strip()
        if "->" not in chunk:
            continue
        left, right = chunk.split("->", 1)
        host = left.rsplit(":", 1)[-1]
        cont = right.split("/")[0]
        if host.isdigit() and cont.isdigit():
            found.append((int(host), int(cont)))
    return found


def look_docker(kind: str) -> dict[str, Any] | None:
    name_hints = {
        "nifi": ("nifi",),
        "ollama": ("ollama", "kd-ollama"),
    }
    image_hints = {
        "nifi": ("nifi",),
        "ollama": ("ollama",),
    }
    want_names = name_hints[kind]
    want_images = image_hints[kind]
    rows = list(docker_ps())
    if kind == "nifi":
        rows.sort(
            key=lambda r: (
                0
                if "idol" in (r["name"] + r["image"] + r.get("service", "")).lower()
                else 1
            )
        )
    for row in rows:
        name = row["name"].lower()
        image = row["image"].lower()
        service = (row.get("service") or "").lower()
        name_hit = any(h in name or service == h for h in want_names)
        image_hit = any(h in image for h in want_images)
        if not (name_hit or image_hit):
            continue
        if any(skip in name for skip in ("nifi-proxy", "nifi-ai", "nifi-kd", "orchestrator")):
            continue
        mapped = published_ports(row["ports"])
        host_port = None
        if kind == "nifi":
            for hp, cp in mapped:
                if hp in BLOCKED_HOST_PORTS:
                    continue
                if cp in (8443, 8080, 8081, 9443):
                    host_port = hp
                    break
            if host_port is None:
                for hp, cp in mapped:
                    if hp in BLOCKED_HOST_PORTS:
                        continue
                    if hp in NIFI_LIKE_CONTAINER_PORTS or cp in NIFI_LIKE_CONTAINER_PORTS:
                        host_port = hp
                        break
        else:
            for hp, cp in mapped:
                if cp == 11434:
                    host_port = hp
                    break
        if host_port is None:
            for hp, _cp in mapped:
                if hp not in BLOCKED_HOST_PORTS:
                    host_port = hp
                    break
        alias = service or row["name"].lstrip("/")
        networks: list[str] = []
        try:
            raw = subprocess.run(
                ["docker", "inspect", row["id"]], capture_output=True, text=True, timeout=8
            ).stdout
            info = json.loads(raw)[0]
            nets = (info.get("NetworkSettings") or {}).get("Networks") or {}
            networks = list(nets.keys())
            # Prefer the real container name for Docker DNS (idol-demo-idol-nifi-1).
            alias = row["name"].lstrip("/")
        except Exception:
            alias = row["name"].lstrip("/")
        return {
            "kind": kind,
            "source": "docker",
            "name": row["name"].lstrip("/"),
            "image": row["image"],
            "host_port": host_port,
            "service": service,
            "alias": alias,
            "networks": networks,
            "container": True,
        }
    return None


def probe_ollama(port: int) -> bool:
    data = http_json(f"http://127.0.0.1:{port}/api/tags")
    return isinstance(data, dict) and "models" in data


def probe_nifi(port: int) -> str | None:
    """Return scheme ('https'/'http') if this port speaks NiFi API."""
    for scheme in ("https", "http"):
        data = http_json(f"{scheme}://127.0.0.1:{port}/nifi-api/access/config")
        if isinstance(data, dict) and (
            "supportsLogin" in data
            or "config" in data
            or "supportsAnonymous" in json.dumps(data)
        ):
            return scheme
        status, body = http_meta(f"{scheme}://127.0.0.1:{port}/nifi-api")
        blob = body.lower()
        if status in (200, 401, 403, 409) and ("nifi" in blob or "unauthorized" in blob or status in (401, 403)):
            # Avoid claiming a random 401 as NiFi unless path looks like the API.
            if "nifi" in blob or status in (200, 409):
                return scheme
        status, body = http_meta(f"{scheme}://127.0.0.1:{port}/nifi")
        if status and "nifi" in body.lower():
            return scheme
    return None


def parse_nifi_url(url: str) -> dict[str, Any] | None:
    url = (url or "").strip()
    if not url:
        return None
    if "://" not in url:
        url = "https://" + url
    parsed = urllib.parse.urlparse(url)
    host = parsed.hostname
    if not host:
        return None
    port = parsed.port or (443 if parsed.scheme == "https" else 80)
    scheme = parsed.scheme or "https"
    api = f"{scheme}://{host}:{port}/nifi-api"
    return {
        "kind": "nifi",
        "source": "external",
        "name": f"{host}:{port}",
        "host": host,
        "host_port": port,
        "scheme": scheme,
        "api": api,
        "ui": f"{scheme}://{host}:{port}/nifi",
        "container": False,
    }


def _stale_host(host: str | None) -> bool:
    return (host or "").lower() in STALE_EXAMPLE_HOSTS


def _localhost_host(host: str | None) -> bool:
    return (host or "").lower() in {"127.0.0.1", "localhost", "host.docker.internal", "::1"}


def attach_docker_identity(target: dict[str, Any], hit: dict[str, Any]) -> dict[str, Any]:
    """Rewrite an external URL so compose talks over Docker DNS + shared network."""
    name = str(hit.get("name") or "nifi")
    nets = list(hit.get("networks") or [])
    preferred = "idol-demo-network" if "idol-demo-network" in nets else (nets[0] if nets else None)
    merged = dict(target)
    merged.update(
        {
            "source": "docker",
            "name": name,
            "alias": name,
            "host": name,
            "networks": nets,
            "docker_network": preferred,
            "container": True,
            "api": f"https://{name}:8443/nifi-api",
            "ui": f"https://{name}:8443/nifi",
            "published_port": hit.get("host_port"),
        }
    )
    return merged


def docker_network_for_ip(ip: str) -> str | None:
    try:
        ids = subprocess.run(
            ["docker", "ps", "-q"], capture_output=True, text=True, timeout=8
        ).stdout.split()
    except Exception:
        return None
    for cid in ids:
        try:
            raw = subprocess.run(
                ["docker", "inspect", cid], capture_output=True, text=True, timeout=8
            ).stdout
            info = json.loads(raw)[0]
        except Exception:
            continue
        nets = (info.get("NetworkSettings") or {}).get("Networks") or {}
        for name, spec in nets.items():
            if (spec or {}).get("IPAddress") == ip:
                return name
    return None


def discover_nifi(
    existing: dict[str, str],
    force_create: bool,
    explicit_url: str | None = None,
    deploy: str = "auto",
) -> dict[str, Any] | None:
    if force_create:
        return None
    explicit = parse_nifi_url(explicit_url or existing.get("NIFI_EXTERNAL_URL", ""))
    docker_hit = look_docker("nifi") if deploy in {"auto", "docker"} else None
    if explicit and _stale_host(str(explicit.get("host"))):
        # Keep the example IP only when it actually answers on this host.
        if not probe_nifi(int(explicit["host_port"])):
            explicit = None
    if explicit:
        host = str(explicit.get("host") or "")
        port = int(explicit.get("host_port") or 0)
        if port in BLOCKED_HOST_PORTS:
            explicit = None
        elif deploy in {"linux", "windows"}:
            explicit["deploy"] = deploy
            return explicit
        elif docker_hit and (
            _localhost_host(host)
            or host == docker_hit.get("name")
            or int(docker_hit.get("host_port") or 0) == port
        ):
            return attach_docker_identity(explicit, docker_hit)
        else:
            net = docker_network_for_ip(host) if _looks_ip(host) else None
            if net:
                explicit["docker_network"] = net
                if docker_hit:
                    return attach_docker_identity(explicit, docker_hit)
            explicit["deploy"] = deploy
            return explicit
    if deploy in {"linux", "windows"}:
        docker_hit = None
    else:
        docker_hit = docker_hit or look_docker("nifi")
    if docker_hit and docker_hit.get("host_port"):
        scheme = probe_nifi(int(docker_hit["host_port"])) or "https"
        docker_hit["scheme"] = scheme
        docker_hit["deploy"] = "docker"
        nets = list(docker_hit.get("networks") or [])
        docker_hit["docker_network"] = (
            "idol-demo-network" if "idol-demo-network" in nets else (nets[0] if nets else None)
        )
        return docker_hit
    if docker_hit:
        # Container exists but no published port — reusable via compose network.
        docker_hit["scheme"] = "https"
        docker_hit["host_port"] = PREFERRED["NIFI_HOST_PORT"]
        docker_hit["internal_only"] = True
        docker_hit["deploy"] = "docker"
        nets = list(docker_hit.get("networks") or [])
        docker_hit["docker_network"] = (
            "idol-demo-network" if "idol-demo-network" in nets else (nets[0] if nets else None)
        )
        return docker_hit

    if deploy == "docker":
        return None

    ports: list[int] = []
    for raw in (
        existing.get("NIFI_HOST_PORT"),
        existing.get("NIFI_EXISTING_PORT"),
    ):
        if raw and raw.isdigit() and int(raw) not in BLOCKED_HOST_PORTS:
            ports.append(int(raw))
    ports.extend(p for p in NIFI_PROBE_PORTS if p not in BLOCKED_HOST_PORTS)
    seen: set[int] = set()
    for port in ports:
        if port in seen or port in BLOCKED_HOST_PORTS:
            continue
        seen.add(port)
        scheme = probe_nifi(port)
        if scheme:
            return {
                "kind": "nifi",
                "source": "host",
                "name": f"host:{port}",
                "host_port": port,
                "scheme": scheme,
                "container": False,
            }
    return None


def discover_ollama(existing: dict[str, str], force_create: bool) -> dict[str, Any] | None:
    if force_create:
        return None
    docker_hit = look_docker("ollama")
    if docker_hit and docker_hit.get("host_port") and probe_ollama(int(docker_hit["host_port"])):
        return docker_hit
    if docker_hit and docker_hit.get("host_port"):
        return docker_hit
    if docker_hit:
        docker_hit["host_port"] = PREFERRED["OLLAMA_HOST_PORT"]
        docker_hit["internal_only"] = True
        return docker_hit

    ports: list[int] = []
    for raw in (existing.get("OLLAMA_HOST_PORT"), existing.get("OLLAMA_EXISTING_PORT")):
        if raw and raw.isdigit():
            ports.append(int(raw))
    ports.extend(OLLAMA_PROBE_PORTS)
    seen: set[int] = set()
    for port in ports:
        if port in seen:
            continue
        seen.add(port)
        if probe_ollama(port):
            return {
                "kind": "ollama",
                "source": "host",
                "name": f"host:{port}",
                "host_port": port,
                "container": False,
            }
    return None


def take_port(name: str, existing: dict[str, str], used: set[int], force: bool, notes: list[str]) -> int:
    """Always publish the documented 27xxx ports so URLs stay stable."""
    preferred = PREFERRED[name]
    used.add(preferred)
    raw = existing.get(name, "").strip()
    if raw.isdigit() and int(raw) != preferred:
        notes.append(f"{name}: ignoring {raw}, pinning {preferred}")
    return preferred


def _looks_ip(host: str) -> bool:
    try:
        socket.inet_aton(host)
        return True
    except OSError:
        return False


def allocate(
    existing: dict[str, str],
    force_nifi: bool,
    force_ollama: bool,
    force_ports: bool,
    nifi_url: str | None = None,
    deploy: str = "auto",
) -> tuple[dict[str, str], list[str], dict[str, Any]]:
    notes: list[str] = []
    used: set[int] = set()

    nifi_found = discover_nifi(
        existing, force_create=force_nifi, explicit_url=nifi_url, deploy=deploy
    )
    ollama_found = discover_ollama(existing, force_create=force_ollama)

    # Local HTTP entry is always OUR proxy on 27111, even when NiFi lives elsewhere.
    local_http_port = take_port("NIFI_HOST_PORT", existing, used, force_ports, notes)

    if nifi_found:
        remote_port = int(nifi_found["host_port"])
        start_nifi = False
        if nifi_found.get("source") == "docker" and not nifi_found.get("api"):
            nifi_found["api"] = f"https://{nifi_found.get('alias') or 'nifi'}:8443/nifi-api"
        notes.append(f"Reusing existing NiFi {nifi_found['name']} — local UI http://localhost:{local_http_port}/nifi")
        nifi_host = str(nifi_found.get("host") or "host.docker.internal")
        if nifi_found.get("source") == "external":
            nifi_upstream = f"{nifi_host}:{remote_port}"
        elif nifi_found.get("source") == "docker":
            alias = nifi_found.get("alias") or nifi_found.get("service") or "nifi"
            nifi_upstream = f"{alias}:8443"
            nets = nifi_found.get("networks") or []
            if nets:
                nifi_found["docker_network"] = (
                    "idol-demo-network" if "idol-demo-network" in nets else nets[0]
                )
        else:
            nifi_upstream = f"host.docker.internal:{remote_port}"
        nifi_tls_port = remote_port
    else:
        nifi_tls_port = take_port("NIFI_TLS_HOST_PORT", existing, used, force_ports, notes)
        start_nifi = True
        nifi_upstream = "nifi:8443"
        notes.append(
            f"No NiFi found — create container TLS :{nifi_tls_port}, open https://localhost:{local_http_port}/nifi"
        )
        remote_port = nifi_tls_port

    if ollama_found:
        ollama_port = int(ollama_found["host_port"])
        used.add(ollama_port)
        start_ollama = False
        notes.append(f"Reusing existing Ollama {ollama_found['name']} on :{ollama_port}")
        if ollama_found.get("source") == "docker" and ollama_found.get("name") in {"ollama", "kd-ollama"}:
            ollama_base = "http://ollama:11434"
            ollama_urls = (
                "http://ollama:11434,"
                f"http://host.docker.internal:{ollama_port},"
                f"http://172.17.0.1:{ollama_port}"
            )
        else:
            ollama_base = f"http://host.docker.internal:{ollama_port}"
            ollama_urls = (
                f"{ollama_base},"
                f"http://172.17.0.1:{ollama_port},"
                "http://ollama:11434"
            )
    else:
        ollama_port = take_port("OLLAMA_HOST_PORT", existing, used, force_ports, notes)
        start_ollama = True
        ollama_base = "http://ollama:11434"
        ollama_urls = (
            "http://ollama:11434,"
            f"http://host.docker.internal:{ollama_port},"
            f"http://172.17.0.1:{ollama_port}"
        )
        notes.append(f"No Ollama found — will create one on host port {ollama_port}")

    proxy_port = local_http_port
    mcp_port = take_port("MCP_HOST_PORT", existing, used, force_ports, notes)
    orch_port = take_port("ORCHESTRATOR_HOST_PORT", existing, used, force_ports, notes)
    ui_port = take_port("UI_HOST_PORT", existing, used, force_ports, notes)

    profiles: list[str] = []
    if start_nifi:
        profiles.append("create-nifi")
    if start_ollama:
        profiles.append("create-ollama")

    env = {
        "NIFI_HOST_PORT": str(local_http_port),
        "NIFI_PROXY_HOST_PORT": str(proxy_port),
        "NIFI_TLS_HOST_PORT": str(nifi_tls_port),
        "NIFI_EXISTING_PORT": str(remote_port),
        "MCP_HOST_PORT": str(mcp_port),
        "OLLAMA_HOST_PORT": str(ollama_port),
        "ORCHESTRATOR_HOST_PORT": str(orch_port),
        "UI_HOST_PORT": str(ui_port),
        "NIFI_WEB_HTTPS_PORT": "8443",
        "NIFI_PUBLIC_URL": f"https://localhost:{local_http_port}/nifi",
        "NIFI_WEB_PROXY_HOST": (
            f"localhost:8443,localhost:{local_http_port},nifi:8443,"
            f"host.docker.internal:{local_http_port},127.0.0.1:{local_http_port}"
        ),
        "NIFI_UPSTREAM": nifi_upstream,
        "NIFI_API_BASE": (
            nifi_found.get("api")
            if nifi_found and nifi_found.get("api")
            else "http://nifi-proxy:8080/nifi-api"
        ),
        "NIFI_BASE_URL": (
            nifi_found.get("api")
            if nifi_found and nifi_found.get("api")
            else "http://nifi-proxy:8080/nifi-api"
        ),
        "NIFI_EXTERNAL_URL": (
            nifi_found.get("ui", "").replace("/nifi", "")
            if nifi_found and nifi_found.get("source") == "external"
            else existing.get("NIFI_EXTERNAL_URL", "")
        ),
        "NIFI_EXTERNAL_API": nifi_found.get("api", "") if nifi_found else "",
        "NIFI_API_BASES": ",".join(
            x
            for x in [
                nifi_found.get("api") if nifi_found else "",
                (
                    f"{nifi_found.get('scheme', 'https')}://host.docker.internal:{remote_port}/nifi-api"
                    if nifi_found and nifi_found.get("source") not in {"docker"}
                    else ""
                ),
                "http://nifi-proxy:8080/nifi-api",
            ]
            if x
        ),
        "NIFI_DEPLOY": deploy if deploy != "auto" else (
            "docker" if nifi_found and nifi_found.get("source") == "docker" else "linux"
        ),
        "NIFI_DOCKER_NETWORK": (
            (nifi_found or {}).get("docker_network")
            or existing.get("NIFI_DOCKER_NETWORK")
            or "kd-nifi-ext"
        )
        if deploy not in {"linux", "windows"}
        else (existing.get("NIFI_DOCKER_NETWORK") or "kd-nifi-ext"),
        "NIFI_DOCKER_NETWORK_EXTERNAL": (
            "true"
            if deploy not in {"linux", "windows"} and (nifi_found or {}).get("docker_network")
            else "false"
        ),
        "START_NIFI": "true" if start_nifi else "false",
        "START_OLLAMA": "true" if start_ollama else "false",
        "NIFI_SOURCE": "new" if start_nifi else str(nifi_found.get("source") if nifi_found else "unknown"),
        "OLLAMA_SOURCE": "new" if start_ollama else str(ollama_found.get("source") if ollama_found else "unknown"),
        "NIFI_EXISTING_NAME": "" if start_nifi else str(nifi_found.get("name") if nifi_found else ""),
        "OLLAMA_EXISTING_NAME": "" if start_ollama else str(ollama_found.get("name") if ollama_found else ""),
        "OLLAMA_BASE_URL": ollama_base,
        "OLLAMA_BASE_URLS": ollama_urls,
        "ORCHESTRATOR_PUBLIC_URL": f"http://localhost:{orch_port}",
        "COMPOSE_PROFILES": ",".join(profiles),
        "NIFI_WAIT_SECONDS": existing.get("NIFI_WAIT_SECONDS", "45") or "45",
        "NIFI_USERNAME": existing.get("NIFI_USERNAME") or "admin",
        "NIFI_PASSWORD": (
            existing.get("NIFI_PASSWORD")
            if existing.get("NIFI_PASSWORD") and existing.get("NIFI_PASSWORD") not in {"changeme12345"}
            else "OpenText2026!"
        ),
    }
    meta = {"nifi": nifi_found, "ollama": ollama_found, "start_nifi": start_nifi, "start_ollama": start_ollama}
    return env, notes, meta


def banner(env: dict[str, str], notes: list[str]) -> str:
    import os, sys
    color = sys.stdout.isatty() and not os.environ.get("NO_COLOR")
    B = "\033[1m" if color else ""
    C = "\033[36m" if color else ""
    G = "\033[32m" if color else ""
    Y = "\033[33m" if color else ""
    M = "\033[35m" if color else ""
    R = "\033[0m" if color else ""
    host = (
        env.get("NIFI_PUBLIC_HOST")
        or os.environ.get("EXTRA_IP_SANS_ENV", "").split(",")[0].strip()
        or os.environ.get("IDOL_NET_HOST_IP", "").strip()
        or "localhost"
    )
    nifi_mode = "CREATE" if env.get("START_NIFI") == "true" else f"REUSE ({env.get('NIFI_EXISTING_NAME') or env.get('NIFI_SOURCE')})"
    ollama_mode = "CREATE" if env.get("START_OLLAMA") == "true" else f"REUSE ({env.get('OLLAMA_EXISTING_NAME') or env.get('OLLAMA_SOURCE')})"
    proxy = env.get("NIFI_PROXY_HOST_PORT") or env.get("NIFI_HOST_PORT") or "27111"
    rows = [
        "",
        f"  {C}{B}Runtime plan{R}",
        f"  {C}------------{R}",
        f"  {B}NiFi{R}     {G}[{nifi_mode}]{R}  https://{host}:{proxy}/nifi",
        f"           {Y}upstream{R}      {env.get('NIFI_UPSTREAM')}  (canvas https://{host}:{proxy}/nifi)",
        f"  {B}Ollama{R}   {G}[{ollama_mode}]{R}  http://{host}:{env['OLLAMA_HOST_PORT']}",
        f"  {B}Orchestrator{R}           http://{host}:{env.get('ORCHESTRATOR_HOST_PORT')}",
        f"  {B}MCP{R}                    http://{host}:{env.get('MCP_HOST_PORT')}/sse",
        f"  {B}Chat UI{R}                http://{host}:{env.get('UI_HOST_PORT')}/",
        f"  {B}NiFi direct{R}            https://{host}:8443/nifi",
        f"  {M}Compose profiles{R}       {env.get('COMPOSE_PROFILES') or '(none — using existing NiFi/Ollama)'}",
        "",
    ]
    if notes:
        rows[1:1] = [f"  {Y}" + " | ".join(notes) + R, ""]
    return "\n".join(rows)


def main() -> int:
    parser = argparse.ArgumentParser(description="Reuse existing NiFi/Ollama or allocate ports for new ones")
    parser.add_argument("--write-env", default=".env")
    parser.add_argument("--json", action="store_true")
    parser.add_argument("--create-nifi", action="store_true", help="Ignore an existing NiFi and create a new one")
    parser.add_argument("--create-ollama", action="store_true", help="Ignore an existing Ollama and create a new one")
    parser.add_argument("--force", action="store_true", help="Re-pick ports for services that will be created")
    parser.add_argument(
        "--nifi-url",
        default=None,
        help="Already-running NiFi UI/API root, e.g. https://127.0.0.1:8443",
    )
    parser.add_argument("--nifi-user", default=None, help="NiFi username (default admin)")
    parser.add_argument("--nifi-password", default=None, help="NiFi password (IDOL demo: OpenText2026!)")
    parser.add_argument(
        "--deploy",
        choices=("auto", "linux", "windows", "docker"),
        default="auto",
        help="Where a remote NiFi is running: linux, windows, or docker",
    )
    parser.add_argument(
        "--location",
        choices=("local", "remote"),
        default=None,
        help="local = start this stack's NiFi container; remote = existing URL/container",
    )
    args = parser.parse_args()

    env_path = Path(args.write_env)
    existing = parse_env(env_path)
    if args.nifi_user:
        existing["NIFI_USERNAME"] = args.nifi_user
    if args.nifi_password:
        existing["NIFI_PASSWORD"] = args.nifi_password
    location = args.location or existing.get("NIFI_LOCATION") or ""
    force_nifi = args.create_nifi or location == "local"
    deploy = "docker" if location == "local" else args.deploy
    if location == "local":
        existing["NIFI_LOCATION"] = "local"
        notes_prefix = "Local NiFi: create compose service nifi (apache/nifi)"
    else:
        existing["NIFI_LOCATION"] = location or "remote"
    env, notes, meta = allocate(
        existing,
        force_nifi=force_nifi,
        force_ollama=args.create_ollama,
        force_ports=args.force,
        nifi_url=None if location == "local" else args.nifi_url,
        deploy=deploy,
    )
    env["NIFI_LOCATION"] = "local" if location == "local" else (location or "remote")
    if location == "local":
        notes.insert(0, notes_prefix)
        env["NIFI_API_BASE"] = "https://nifi:8443/nifi-api"
        env["NIFI_BASE_URL"] = "https://nifi:8443/nifi-api"
        env["NIFI_UPSTREAM"] = "nifi:8443"
        env["NIFI_API_BASES"] = "https://nifi:8443/nifi-api,http://nifi-proxy:8080/nifi-api"
        # Never reuse idol-demo-network for a stack-owned NiFi. That name already
        # exists from the IDOL demo and Compose cannot relabel it as nifi-ext.
        env["NIFI_DOCKER_NETWORK"] = "kd-nifi-ext"
        env["NIFI_DOCKER_NETWORK_EXTERNAL"] = "false"
        env["NIFI_EXISTING_NAME"] = "nifi"
        env["START_NIFI"] = "true"
    write_env(env_path, env)
    payload = {"env_file": str(env_path), "notes": notes, "ports": env, "discovered": meta}
    env_path.with_name("ports.json").write_text(json.dumps(payload, indent=2, default=str) + "\n", encoding="utf-8")

    if args.json:
        print(json.dumps(payload, indent=2, default=str))
    else:
        print(f"Wrote {env_path} and {env_path.with_name('ports.json')}")
        print(banner(env, notes))
    return 0


if __name__ == "__main__":
    sys.exit(main())
