#!/usr/bin/env bash
# Install KD Enterprise Search as a systemd service that runs ./serve.sh
set -euo pipefail

if [[ "$(id -u)" -ne 0 ]]; then
  echo "Run as root:  sudo $0 [/absolute/path/to/TAX_GOV_AE]"
  exit 1
fi

REPO="${1:-}"
if [[ -z "$REPO" ]]; then
  # Default: parent of deploy/systemd when script lives in the repo
  HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  REPO="$(cd "$HERE/../.." && pwd)"
fi

APP_DIR="$REPO/apps/web"
SERVICE_SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/kd-enterprise-search.service"
ENV_SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/kd-enterprise-search.env"
UNIT_DST=/etc/systemd/system/kd-enterprise-search.service
ENV_DST=/etc/default/kd-enterprise-search

if [[ ! -x "$APP_DIR/serve.sh" && ! -f "$APP_DIR/serve.sh" ]]; then
  echo "ERROR: serve.sh not found at $APP_DIR/serve.sh"
  exit 1
fi
chmod +x "$APP_DIR/serve.sh" "$APP_DIR/sync-config.sh" "$APP_DIR/restart.sh" 2>/dev/null || true

# Detect a Node 22 binary if possible
NODE_BIN_DIR=""
if command -v node >/dev/null 2>&1; then
  NODE_BIN_DIR="$(dirname "$(command -v node)")"
fi
# Common nvm location for the service User=
for cand in /home/ubuntu/.nvm/versions/node/*/bin /root/.nvm/versions/node/*/bin; do
  if [[ -x "${cand}/node" ]]; then
    # Prefer v22*
    if [[ "$cand" == *"/v22"* ]] || [[ -z "$NODE_BIN_DIR" ]]; then
      NODE_BIN_DIR="$cand"
    fi
  fi
done 2>/dev/null || true

# Resolve service User= from unit file default
SVC_USER=ubuntu
if ! id "$SVC_USER" >/dev/null 2>&1; then
  if id ec2-user >/dev/null 2>&1; then
    SVC_USER=ec2-user
  elif id node >/dev/null 2>&1; then
    SVC_USER=node
  else
    SVC_USER="$(logname 2>/dev/null || echo root)"
  fi
fi

echo "Repo:     $REPO"
echo "App dir:  $APP_DIR"
echo "User:     $SVC_USER"
echo "Node bin: ${NODE_BIN_DIR:-'(system PATH)'}"

# Write environment file
cat > "$ENV_DST" <<ENV
# Generated by install-service.sh — $(date -Is)
APP_DIR=$APP_DIR
NODE_BIN_DIR=$NODE_BIN_DIR
PORT=4200
HOST=0.0.0.0
ENV
chmod 644 "$ENV_DST"

# Write unit with concrete paths / user
sed \
  -e "s|User=ubuntu|User=$SVC_USER|" \
  -e "s|Group=ubuntu|Group=$SVC_USER|" \
  -e "s|WorkingDirectory=/opt/TAX_GOV_AE/apps/web|WorkingDirectory=$APP_DIR|" \
  -e "s|file:///opt/TAX_GOV_AE/docs/RUNBOOK.md|file://$REPO/docs/RUNBOOK.md|" \
  "$SERVICE_SRC" > "$UNIT_DST"

# Fix APP_DIR default inside ExecStart bash -lc as well
sed -i "s|/opt/TAX_GOV_AE/apps/web|$APP_DIR|g" "$UNIT_DST"

chmod 644 "$UNIT_DST"

systemctl daemon-reload
systemctl enable kd-enterprise-search.service
systemctl restart kd-enterprise-search.service

echo
echo "Service installed and started."
echo "  status:  systemctl status kd-enterprise-search"
echo "  logs:    journalctl -u kd-enterprise-search -f"
echo "  stop:    systemctl stop kd-enterprise-search"
echo "  URL:     http://$(hostname -I 2>/dev/null | awk '{print $1}'):4200/  or http://localhost:4200/"
