"""Canonical Knowledge Discovery 26.3 capability catalog.

Only documented ACI / service / index actions are listed. Documentation URLs
prefer the 26.3 portal when the page is published; inherited 26.1/26.2 Help
topics are used only when the action still exists in 26.3.
"""

from __future__ import annotations

from typing import Any

DOC_PORTAL_26_3 = "https://www.microfocus.com/documentation/idol/knowledge-discovery-26.3"
DOC_PORTAL_26_2 = "https://www.microfocus.com/documentation/idol/knowledge-discovery-26.2"
DOC_PORTAL_26_1 = "https://www.microfocus.com/documentation/idol/knowledge-discovery-26.1"
PRODUCT_PAGE = "https://www.opentext.com/products/knowledge-discovery"
WHATS_NEW_26_3 = "https://blogs.opentext.com/whats-new-in-opentext-knowledge-discovery-idol/"
ACI_INTRO_26_2 = f"{DOC_PORTAL_26_2}/IDOLProxy_26.2_Documentation/Help/Content/Introduction/Getting_Started.htm"
CONTENT_QUERY_26_1 = f"{DOC_PORTAL_26_1}/Content_26.1_Documentation/Help/Content/Actions/QueryTypes/Case_Sensitive_Search.htm"
FIELDTEXT_26_1 = f"{DOC_PORTAL_26_1}/Content_26.1_Documentation/Help/Content/Actions/Term/ActionParameters/FieldText.htm"
QUERY_SUMMARY_26_1 = f"{DOC_PORTAL_26_1}/Content_26.1_Documentation/Help/Content/Part%20-%20Results/Customize/About_the_QuerySumma.htm"
MEDIA_RN_26_2 = f"{DOC_PORTAL_26_2}/IDOLReleaseNotes_26.2_Documentation/idol/Content/Servers/MediaServer.htm"
SECURITY_26_1 = f"{DOC_PORTAL_26_1}/Content_26.1_Documentation/Guides/GettingStarted/Content/IDOL_Systems/IDOL_Systems/IDOL_Text_Security.htm"
DAH_26_3 = f"{DOC_PORTAL_26_3}"
NIFI_26_3 = f"{DOC_PORTAL_26_3}"
FCE_26_3 = "https://www.microfocus.com/documentation/idol/file-content-extraction-26.3"
IDOL_DOCS_INDEX = "https://www.microfocus.com/documentation/idol/"

ALL_26 = ["26.1", "26.2", "26.3"]


def _cap(
    *,
    id: str,
    display_name: str,
    category: str,
    component: str,
    action: str,
    required: list[str],
    optional: list[str],
    documentation: str,
    mcp_tool: str,
    mcp_skill: str,
    rw: str = "read",
    destructive: bool = False,
    http_method: str = "GET",
    port_role: str = "aci",
    api_type: str = "aci_action",
    supported_versions: list[str] | None = None,
    deprecated: bool = False,
    version_notes: dict[str, str] | None = None,
    introduced: str | None = None,
    examples: list[dict[str, Any]] | None = None,
    implementation_status: str = "implemented",
) -> dict[str, Any]:
    return {
        "id": id,
        "display_name": display_name,
        "category": category,
        "component": component,
        "component_version": "26.3",
        "api_type": api_type,
        "http_method": http_method,
        "endpoint": f"action={action}",
        "action": action,
        "port_role": port_role,
        "required_parameters": required,
        "optional_parameters": optional,
        "request_format": "aci_query_or_form",
        "response_format": "xml_or_json",
        "authentication_requirements": ["optional_aci_encryption", "optional_securityinfo"],
        "permissions": [],
        "destructive": destructive,
        "read_write": rw,
        "supported_versions": supported_versions or list(ALL_26),
        "deprecated": deprecated,
        "introduced": introduced,
        "version_notes": version_notes or {},
        "documentation": documentation,
        "implementation_status": implementation_status,
        "test_status": "unit",
        "mcp_tool": mcp_tool,
        "mcp_skill": mcp_skill,
        "examples": examples or [],
    }


def build_capabilities() -> list[dict[str, Any]]:
    caps: list[dict[str, Any]] = []

    # ------------------------------------------------------------------
    # Platform / ACI framework
    # ------------------------------------------------------------------
    for component, tool in (
        ("Content", "kd_content_status"),
        ("Community", "kd_community_status"),
        ("Category", "kd_category_status"),
        ("Agentstore", "kd_agentstore_status"),
        ("View", "kd_view_status"),
        ("QMS", "kd_qms_status"),
        ("DAH", "kd_dah_status"),
        ("DIH", "kd_dih_status"),
        ("MediaServer", "kd_media_status"),
        ("Eduction", "kd_eduction_status"),
        ("CFS", "kd_cfs_status"),
        ("LicenseServer", "kd_license_status"),
        ("Proxy", "kd_proxy_status"),
        ("AnswerServer", "kd_answer_status"),
        ("KnowledgeGraph", "kd_kg_status"),
        ("OmniGroupServer", "kd_ogs_status"),
    ):
        caps.append(
            _cap(
                id=f"{component.lower()}.getstatus",
                display_name=f"{component} GetStatus",
                category="administration",
                component=component,
                action="GetStatus",
                required=[],
                optional=["ResponseFormat"],
                documentation=ACI_INTRO_26_2,
                mcp_tool="kd_component_health",
                mcp_skill="kd_service_discovery",
            )
        )
        caps.append(
            _cap(
                id=f"{component.lower()}.getversion",
                display_name=f"{component} GetVersion",
                category="administration",
                component=component,
                action="GetVersion",
                required=[],
                optional=["ResponseFormat"],
                documentation=ACI_INTRO_26_2,
                mcp_tool="kd_component_version",
                mcp_skill="kd_service_discovery",
            )
        )
        caps.append(
            _cap(
                id=f"{component.lower()}.getlicenseinfo",
                display_name=f"{component} GetLicenseInfo",
                category="administration",
                component=component,
                action="GetLicenseInfo",
                required=[],
                optional=["ResponseFormat"],
                documentation=ACI_INTRO_26_2,
                mcp_tool="kd_license_status",
                mcp_skill="kd_administration",
            )
        )
        caps.append(
            _cap(
                id=f"{component.lower()}.getallactions",
                display_name=f"{component} GetAllActions",
                category="administration",
                component=component,
                action="GetAllActions",
                required=[],
                optional=["ResponseFormat"],
                documentation=ACI_INTRO_26_2,
                mcp_tool="kd_list_component_actions",
                mcp_skill="kd_api_discovery",
            )
        )

    # ------------------------------------------------------------------
    # Content search / retrieve
    # ------------------------------------------------------------------
    query_optional = [
        "Text",
        "FieldText",
        "DatabaseMatch",
        "MaxResults",
        "Start",
        "MinScore",
        "Print",
        "PrintFields",
        "Highlight",
        "Summary",
        "QuerySummary",
        "Combine",
        "Sort",
        "Predict",
        "TotalResults",
        "SecurityInfo",
        "StateMatchID",
        "MatchReference",
        "MatchID",
        "DontMatchID",
        "DontMatchReference",
        "LanguageType",
        "AnyLanguage",
        "Stemming",
        "CaseSensitive",
        "Synonym",
        "XPath",
        "XMLMeta",
        "ResponseFormat",
        "OutputEncoding",
        "StoreState",
        "StoredStateTokenLifetime",
        "LinkField",
        "AutoSpellCheck",
        "DREQuery",
        "UseVectors",
    ]
    caps += [
        _cap(
            id="content.query",
            display_name="Content Query",
            category="search",
            component="Content",
            action="Query",
            required=[],
            optional=query_optional,
            documentation=CONTENT_QUERY_26_1,
            mcp_tool="kd_content_query",
            mcp_skill="idol_content_search",
            examples=[{"Text": "knowledge discovery", "MaxResults": 10, "Print": "fields"}],
            version_notes={
                "26.3": "Query remains the primary Content search action. UseVectors applies to TermGetBest/Suggest rather than Query itself.",
            },
        ),
        _cap(
            id="content.getcontent",
            display_name="Content GetContent",
            category="retrieve",
            component="Content",
            action="GetContent",
            required=[],
            optional=["ID", "Reference", "Print", "PrintFields", "Highlight", "SecurityInfo", "ResponseFormat"],
            documentation=f"{DOC_PORTAL_26_1}/Content_26.1_Documentation/Help/Content/Part%20-%20Results/Customize/About_the_QuerySumma.htm",
            mcp_tool="kd_content_get",
            mcp_skill="idol_content_retrieve",
            examples=[{"ID": "1", "Print": "all"}],
        ),
        _cap(
            id="content.suggest",
            display_name="Content/DAH Suggest",
            category="similarity",
            component="Content",
            action="Suggest",
            required=[],
            optional=["ID", "Reference", "MaxResults", "Print", "DatabaseMatch", "SecurityInfo", "UseVectors", "ResponseFormat"],
            documentation=WHATS_NEW_26_3,
            mcp_tool="kd_content_suggest",
            mcp_skill="idol_content_similarity",
            version_notes={
                "26.3": "Suggest on DAH supports UseVectors. Powered by TermGetBest, which also accepts UseVectors.",
            },
            examples=[{"ID": "12", "MaxResults": 5}],
        ),
        _cap(
            id="content.suggestontext",
            display_name="Content SuggestOnText",
            category="similarity",
            component="Content",
            action="SuggestOnText",
            required=["Text"],
            optional=["MaxResults", "Print", "DatabaseMatch", "SecurityInfo", "UseVectors", "ResponseFormat"],
            documentation=WHATS_NEW_26_3,
            mcp_tool="kd_content_suggest_on_text",
            mcp_skill="idol_content_similarity",
        ),
        _cap(
            id="content.highlight",
            display_name="Content Highlight",
            category="search",
            component="Content",
            action="Highlight",
            required=["Text"],
            optional=["HighlightText", "StartTag", "EndTag", "ResponseFormat"],
            documentation=f"{DOC_PORTAL_26_1}/Category_26.1_Documentation/Help/Content/Shared_Admin/IDOLOperations/_ADM_TextAnalytics.htm",
            mcp_tool="kd_content_highlight",
            mcp_skill="idol_content_search",
        ),
        _cap(
            id="content.summarize",
            display_name="Content Summarize",
            category="search",
            component="Content",
            action="Summarize",
            required=[],
            optional=["Text", "ID", "Reference", "Summary", "Sentences", "Characters", "ResponseFormat"],
            documentation=QUERY_SUMMARY_26_1,
            mcp_tool="kd_content_summarize",
            mcp_skill="idol_content_search",
        ),
        _cap(
            id="content.termgetbest",
            display_name="Content TermGetBest",
            category="text_analytics",
            component="Content",
            action="TermGetBest",
            required=[],
            optional=["Text", "ID", "Reference", "MaxTerms", "UseVectors", "ResponseFormat"],
            documentation=WHATS_NEW_26_3,
            mcp_tool="kd_content_term_get_best",
            mcp_skill="idol_content_search",
            version_notes={"26.3": "UseVectors returns best vectors as well as best terms."},
        ),
        _cap(
            id="content.termgetinfo",
            display_name="Content TermGetInfo",
            category="text_analytics",
            component="Content",
            action="TermGetInfo",
            required=["Text"],
            optional=["ResponseFormat"],
            documentation=CONTENT_QUERY_26_1,
            mcp_tool="kd_content_term_get_info",
            mcp_skill="idol_content_search",
        ),
        _cap(
            id="content.getquerytagvalues",
            display_name="Content GetQueryTagValues",
            category="parametric",
            component="Content",
            action="GetQueryTagValues",
            required=["FieldName"],
            optional=["Text", "FieldText", "DatabaseMatch", "MaxValues", "Sort", "SecurityInfo", "ResponseFormat"],
            documentation=FIELDTEXT_26_1,
            mcp_tool="kd_content_parametric",
            mcp_skill="idol_content_parametric",
        ),
        _cap(
            id="content.documentstats",
            display_name="Content DocumentStats",
            category="administration",
            component="Content",
            action="DocumentStats",
            required=[],
            optional=["DatabaseMatch", "ResponseFormat"],
            documentation=ACI_INTRO_26_2,
            mcp_tool="kd_content_index_status",
            mcp_skill="idol_content_admin",
        ),
        _cap(
            id="content.termexpand",
            display_name="Content TermExpand",
            category="text_analytics",
            component="Content",
            action="TermExpand",
            required=["Text"],
            optional=["FieldText", "MaxTerms", "Type", "ResponseFormat"],
            documentation=FIELDTEXT_26_1,
            mcp_tool="kd_content_term_expand",
            mcp_skill="idol_content_search",
        ),
        _cap(
            id="content.gettagvalues",
            display_name="Content GetTagValues",
            category="parametric",
            component="Content",
            action="GetTagValues",
            required=["FieldName"],
            optional=["MaxValues", "Sort", "DatabaseMatch", "ResponseFormat"],
            documentation=FIELDTEXT_26_1,
            mcp_tool="kd_content_parametric",
            mcp_skill="idol_content_parametric",
        ),
    ]

    # ------------------------------------------------------------------
    # Content index actions (index port)
    # ------------------------------------------------------------------
    index_docs = f"{DOC_PORTAL_26_2}/Content_26.2_Documentation/Guides/GettingStarted/Content/IDOL_Systems/Intro/Index_and_Query.htm"
    caps += [
        _cap(
            id="content.dreadddata",
            display_name="Index DREADDDATA",
            category="ingest",
            component="Content",
            action="DREADDDATA",
            required=[],
            optional=["DREDbName", "KillDuplicates"],
            documentation=index_docs,
            mcp_tool="kd_content_index_data",
            mcp_skill="idol_content_index",
            rw="write",
            http_method="POST",
            port_role="index",
            api_type="index_action",
        ),
        _cap(
            id="content.dreadd",
            display_name="Index DREADD",
            category="ingest",
            component="Content",
            action="DREADD",
            required=["FileName"],
            optional=["DREDbName", "KillDuplicates"],
            documentation=index_docs,
            mcp_tool="kd_content_index_file",
            mcp_skill="idol_content_index",
            rw="write",
            http_method="POST",
            port_role="index",
            api_type="index_action",
        ),
        _cap(
            id="content.dredeletedoc",
            display_name="Index DREDELETEDOC",
            category="ingest",
            component="Content",
            action="DREDELETEDOC",
            required=["Docs"],
            optional=["DREDbName"],
            documentation=index_docs,
            mcp_tool="kd_content_delete",
            mcp_skill="idol_content_index",
            rw="write",
            destructive=True,
            http_method="POST",
            port_role="index",
            api_type="index_action",
        ),
        _cap(
            id="content.dredeleteref",
            display_name="Index DREDELETEREF",
            category="ingest",
            component="Content",
            action="DREDELETEREF",
            required=["Docs"],
            optional=["DREDbName"],
            documentation=index_docs,
            mcp_tool="kd_content_delete",
            mcp_skill="idol_content_index",
            rw="write",
            destructive=True,
            http_method="POST",
            port_role="index",
            api_type="index_action",
        ),
        _cap(
            id="content.drereplace",
            display_name="Index DREREPLACE",
            category="ingest",
            component="Content",
            action="DREREPLACE",
            required=[],
            optional=["DatabaseMatch"],
            documentation="https://cabs.microfocus.com/documentation/idol/IDOL_23_2/Content_23.2_Documentation/Help/Content/Part%20-%20Administration/Administration/Change_Document_Fiel.htm",
            mcp_tool="kd_content_replace_fields",
            mcp_skill="idol_content_index",
            rw="write",
            http_method="POST",
            port_role="index",
            api_type="index_action",
        ),
        _cap(
            id="content.dresync",
            display_name="Index DRESYNC",
            category="administration",
            component="Content",
            action="DRESYNC",
            required=[],
            optional=[],
            documentation=index_docs,
            mcp_tool="kd_content_sync",
            mcp_skill="idol_content_admin",
            rw="write",
            http_method="GET",
            port_role="index",
            api_type="index_action",
        ),
        _cap(
            id="content.drecompact",
            display_name="Index DRECOMPACT",
            category="administration",
            component="Content",
            action="DRECOMPACT",
            required=[],
            optional=[],
            documentation=index_docs,
            mcp_tool="kd_content_compact",
            mcp_skill="idol_content_admin",
            rw="write",
            destructive=True,
            http_method="GET",
            port_role="index",
            api_type="index_action",
        ),
        _cap(
            id="content.dreinitial",
            display_name="Index DREINITIAL",
            category="administration",
            component="Content",
            action="DREINITIAL",
            required=[],
            optional=[],
            documentation=index_docs,
            mcp_tool="kd_content_initialize",
            mcp_skill="idol_content_admin",
            rw="write",
            destructive=True,
            http_method="GET",
            port_role="index",
            api_type="index_action",
        ),
        _cap(
            id="content.drecreatedbase",
            display_name="Index DRECREATEDBASE",
            category="administration",
            component="Content",
            action="DRECREATEDBASE",
            required=["DREDbName"],
            optional=[],
            documentation=index_docs,
            mcp_tool="kd_content_create_database",
            mcp_skill="idol_content_admin",
            rw="write",
            http_method="GET",
            port_role="index",
            api_type="index_action",
        ),
        _cap(
            id="content.dredeldbase",
            display_name="Index DREDELDBASE",
            category="administration",
            component="Content",
            action="DREDELDBASE",
            required=["DREDbName"],
            optional=[],
            documentation=index_docs,
            mcp_tool="kd_content_delete_database",
            mcp_skill="idol_content_admin",
            rw="write",
            destructive=True,
            http_method="GET",
            port_role="index",
            api_type="index_action",
        ),
    ]

    # ------------------------------------------------------------------
    # Community / security
    # ------------------------------------------------------------------
    caps += [
        _cap(
            id="community.userread",
            display_name="Community UserRead",
            category="security",
            component="Community",
            action="UserRead",
            required=["UserName"],
            optional=["Security", "ResponseFormat"],
            documentation=SECURITY_26_1,
            mcp_tool="kd_community_user_read",
            mcp_skill="kd_security",
            version_notes={"26.3": "OTDS integration can accept username/password via OTDSUserField."},
        ),
        _cap(
            id="community.security",
            display_name="Community Security / SecurityInfo",
            category="security",
            component="Community",
            action="Security",
            required=["UserName"],
            optional=["Password", "Repository", "ResponseFormat"],
            documentation=SECURITY_26_1,
            mcp_tool="kd_security_info",
            mcp_skill="kd_security",
        ),
        _cap(
            id="community.useradd",
            display_name="Community UserAdd",
            category="security",
            component="Community",
            action="UserAdd",
            required=["UserName"],
            optional=["Password", "Email", "ResponseFormat"],
            documentation=SECURITY_26_1,
            mcp_tool="kd_community_user_add",
            mcp_skill="kd_security",
            rw="write",
        ),
        _cap(
            id="ogs.getstatus",
            display_name="OmniGroupServer health",
            category="security",
            component="OmniGroupServer",
            action="GetStatus",
            required=[],
            optional=["ResponseFormat"],
            documentation=SECURITY_26_1,
            mcp_tool="kd_component_health",
            mcp_skill="kd_security",
        ),
    ]

    # ------------------------------------------------------------------
    # Category / classification
    # ------------------------------------------------------------------
    cat_docs = f"{DOC_PORTAL_26_1}/Category_26.1_Documentation/Help/Content/Shared_Admin/IDOLOperations/_ADM_SearchAndRetrieval.htm"
    caps += [
        _cap(
            id="category.suggestfromtext",
            display_name="CategorySuggestFromText",
            category="classification",
            component="Category",
            action="CategorySuggestFromText",
            required=["QueryText"],
            optional=["NumResults", "ResponseFormat"],
            documentation=cat_docs,
            mcp_tool="kd_category_suggest_from_text",
            mcp_skill="kd_classification",
        ),
        _cap(
            id="category.query",
            display_name="CategoryQuery",
            category="classification",
            component="Category",
            action="CategoryQuery",
            required=[],
            optional=["Text", "Category", "NumResults", "ResponseFormat"],
            documentation=cat_docs,
            mcp_tool="kd_category_query",
            mcp_skill="kd_classification",
        ),
        _cap(
            id="category.list",
            display_name="CategoryList",
            category="classification",
            component="Category",
            action="CategoryList",
            required=[],
            optional=["Parent", "ResponseFormat"],
            documentation=cat_docs,
            mcp_tool="kd_category_list",
            mcp_skill="kd_classification",
        ),
        _cap(
            id="category.getdetails",
            display_name="CategoryGetDetails",
            category="classification",
            component="Category",
            action="CategoryGetDetails",
            required=["Category"],
            optional=["ResponseFormat"],
            documentation=cat_docs,
            mcp_tool="kd_category_get_details",
            mcp_skill="kd_classification",
        ),
        _cap(
            id="category.create",
            display_name="CategoryCreate",
            category="classification",
            component="Category",
            action="CategoryCreate",
            required=["Name"],
            optional=["Parent", "ResponseFormat"],
            documentation=cat_docs,
            mcp_tool="kd_category_create",
            mcp_skill="kd_classification",
            rw="write",
        ),
        _cap(
            id="category.delete",
            display_name="CategoryDelete",
            category="classification",
            component="Category",
            action="CategoryDelete",
            required=["Category"],
            optional=["ResponseFormat"],
            documentation=cat_docs,
            mcp_tool="kd_category_delete",
            mcp_skill="kd_classification",
            rw="write",
            destructive=True,
        ),
    ]

    # ------------------------------------------------------------------
    # QMS / DAH / DIH / View / Agentstore
    # ------------------------------------------------------------------
    caps += [
        _cap(
            id="qms.query",
            display_name="QMS Query",
            category="search",
            component="QMS",
            action="Query",
            required=[],
            optional=query_optional,
            documentation=f"{DOC_PORTAL_26_1}/Category_26.1_Documentation/Help/Content/Shared_Admin/IDOLOperations/_ADM_TextAnalytics.htm",
            mcp_tool="kd_qms_query",
            mcp_skill="kd_query_manipulation",
        ),
        _cap(
            id="dah.query",
            display_name="DAH Query",
            category="search",
            component="DAH",
            action="Query",
            required=[],
            optional=query_optional,
            documentation=f"{DOC_PORTAL_26_2}/Content_26.2_Documentation/Guides/GettingStarted/Content/IDOL_Systems/IDOL_Systems/Distributed_Setup.htm",
            mcp_tool="kd_dah_query",
            mcp_skill="kd_distributed_search",
        ),
        _cap(
            id="dah.suggest",
            display_name="DAH Suggest",
            category="similarity",
            component="DAH",
            action="Suggest",
            required=[],
            optional=["ID", "Reference", "MaxResults", "UseVectors", "SecurityInfo", "ResponseFormat"],
            documentation=WHATS_NEW_26_3,
            mcp_tool="kd_dah_suggest",
            mcp_skill="kd_distributed_search",
            version_notes={"26.3": "UseVectors added for vector similarity through DAH."},
            introduced="26.3",
        ),
        _cap(
            id="dih.dreadddata",
            display_name="DIH DREADDDATA",
            category="ingest",
            component="DIH",
            action="DREADDDATA",
            required=[],
            optional=["DREDbName"],
            documentation=f"{DOC_PORTAL_26_2}/Content_26.2_Documentation/Guides/GettingStarted/Content/IDOL_Systems/IDOL_Systems/Distributed_Setup.htm",
            mcp_tool="kd_dih_index_data",
            mcp_skill="kd_distributed_index",
            rw="write",
            http_method="POST",
            port_role="index",
            api_type="index_action",
        ),
        _cap(
            id="view.view",
            display_name="View document",
            category="retrieve",
            component="View",
            action="View",
            required=["Reference"],
            optional=["NoAci", "Highlight", "StartTag", "EndTag", "OutputType", "ResponseFormat"],
            documentation=f"{DOC_PORTAL_26_2}/View_26.2_Documentation/Help/Content/Part%20-%20Results/Retrieval/Types_of_Matches.htm",
            mcp_tool="kd_view_document",
            mcp_skill="idol_content_retrieve",
        ),
        _cap(
            id="agentstore.query",
            display_name="Agentstore Query",
            category="search",
            component="Agentstore",
            action="Query",
            required=[],
            optional=["Text", "MaxResults", "Print", "ResponseFormat"],
            documentation=f"{DOC_PORTAL_26_2}/View_26.2_Documentation/Help/Content/Part%20-%20Results/Retrieval/Types_of_Matches.htm",
            mcp_tool="kd_agentstore_query",
            mcp_skill="kd_community_agents",
        ),
    ]

    # ------------------------------------------------------------------
    # Eduction
    # ------------------------------------------------------------------
    eduction_docs = f"{DOC_PORTAL_26_3}"
    caps += [
        _cap(
            id="eduction.educefromtext",
            display_name="EduceFromText",
            category="entity_extraction",
            component="Eduction",
            action="EduceFromText",
            required=["Text"],
            optional=["Grammars", "Entities", "Document", "ResponseFormat"],
            documentation=WHATS_NEW_26_3,
            mcp_tool="kd_educe_text",
            mcp_skill="kd_entity_extraction",
            version_notes={
                "26.3": "Saudi Arabia PII grammars; Oman/UAE improvements; format subtypes; ITAR munitions dictionary.",
            },
        ),
        _cap(
            id="eduction.educefromfile",
            display_name="EduceFromFile",
            category="entity_extraction",
            component="Eduction",
            action="EduceFromFile",
            required=["FileName"],
            optional=["Grammars", "Entities", "ResponseFormat"],
            documentation=WHATS_NEW_26_3,
            mcp_tool="kd_educe_file",
            mcp_skill="kd_entity_extraction",
        ),
    ]

    # ------------------------------------------------------------------
    # Media Server
    # ------------------------------------------------------------------
    media_help = f"{DOC_PORTAL_26_2}/MediaServer_26.2_Documentation/Help/Content/Appendixes/OCR_Supported_Languages.htm"
    ocr_help = f"{DOC_PORTAL_26_1}/MediaServer_26.1_Documentation/Help/Content/Configuration/Analysis/OCR/_OCR.htm"
    caps += [
        _cap(
            id="media.process",
            display_name="Media Server Process",
            category="rich_media",
            component="MediaServer",
            action="Process",
            required=[],
            optional=[
                "Source",
                "SourcePath",
                "SourceURL",
                "Config",
                "ConfigName",
                "Persist",
                "Priority",
                "Token",
                "ResponseFormat",
            ],
            documentation=media_help,
            mcp_tool="kd_media_process",
            mcp_skill="kd_rich_media",
            version_notes={
                "26.2": "ImageDescription engine added; Legacy STT removed.",
                "26.3": "Speech Medium/Large combined; OCR languages expanded; speech ~3x faster.",
            },
        ),
        _cap(
            id="media.queueinfo",
            display_name="Media Server QueueInfo",
            category="rich_media",
            component="MediaServer",
            action="QueueInfo",
            required=[],
            optional=["QueueAction", "QueueName", "Token", "State", "MaxResults", "ResponseFormat"],
            documentation="https://cabs.microfocus.com/documentation/idol/IDOL_24_4/WebExConnector_24.4_Documentation/Help/Content/Actions/General/_ACI_QueueInfo.htm",
            mcp_tool="kd_media_queue_info",
            mcp_skill="kd_rich_media",
        ),
        _cap(
            id="media.ocr",
            display_name="Media OCR (Process + OCR engine)",
            category="rich_media",
            component="MediaServer",
            action="Process",
            required=[],
            optional=["SourcePath", "SourceURL", "Languages", "OcrMode", "Config", "ResponseFormat"],
            documentation=ocr_help,
            mcp_tool="kd_media_ocr",
            mcp_skill="kd_ocr",
            version_notes={
                "26.3": "Adds hy, az, ka, id, kk, ms, mn, tg, uz OCR languages.",
            },
        ),
        _cap(
            id="media.speech",
            display_name="Media speech-to-text",
            category="rich_media",
            component="MediaServer",
            action="Process",
            required=[],
            optional=["SourcePath", "SourceURL", "LanguagePack", "ModelSize", "ModelVersion", "Config", "ResponseFormat"],
            documentation=MEDIA_RN_26_2,
            mcp_tool="kd_media_speech_to_text",
            mcp_skill="kd_speech_to_text",
            version_notes={
                "26.2": "Legacy model removed.",
                "26.3": "Medium and Large combined into one model; previous names still resolve.",
            },
        ),
        _cap(
            id="media.face_detect",
            display_name="Media face detection",
            category="rich_media",
            component="MediaServer",
            action="Process",
            required=[],
            optional=["SourcePath", "SourceURL", "Config", "ResponseFormat"],
            documentation=media_help,
            mcp_tool="kd_media_face_detect",
            mcp_skill="kd_face_analysis",
        ),
        _cap(
            id="media.object",
            display_name="Media object recognition",
            category="rich_media",
            component="MediaServer",
            action="Process",
            required=[],
            optional=["SourcePath", "SourceURL", "Config", "ResponseFormat"],
            documentation=MEDIA_RN_26_2,
            mcp_tool="kd_media_object_recognize",
            mcp_skill="kd_object_recognition",
        ),
        _cap(
            id="media.numberplate",
            display_name="Media number plate recognition",
            category="rich_media",
            component="MediaServer",
            action="Process",
            required=[],
            optional=["SourcePath", "SourceURL", "Config", "Region", "ResponseFormat"],
            documentation=WHATS_NEW_26_3,
            mcp_tool="kd_media_number_plate",
            mcp_skill="kd_surveillance",
        ),
        _cap(
            id="media.image_description",
            display_name="Media ImageDescription",
            category="rich_media",
            component="MediaServer",
            action="Process",
            required=[],
            optional=["SourcePath", "SourceURL", "Config", "ResponseFormat"],
            documentation=MEDIA_RN_26_2,
            mcp_tool="kd_media_image_description",
            mcp_skill="kd_image_description",
            supported_versions=["26.2", "26.3"],
            introduced="26.2",
        ),
        _cap(
            id="media.build_object_class",
            display_name="BuildObjectClassRecognizer",
            category="rich_media",
            component="MediaServer",
            action="BuildObjectClassRecognizer",
            required=["Identifier"],
            optional=["ResponseFormat"],
            documentation=MEDIA_RN_26_2,
            mcp_tool="kd_media_build_object_class",
            mcp_skill="kd_object_recognition",
            rw="write",
            supported_versions=["26.2", "26.3"],
            introduced="26.2",
        ),
    ]

    # ------------------------------------------------------------------
    # CFS / connectors / ingest
    # ------------------------------------------------------------------
    cfs_docs = f"{DOC_PORTAL_26_2}/CFS_26.2_Documentation/Help/Content/ProcessDocuments/Disable_Filter_Extract.htm"
    caps += [
        _cap(
            id="cfs.synchronize",
            display_name="CFS/Connector Synchronize",
            category="ingest",
            component="CFS",
            action="Synchronize",
            required=[],
            optional=["Identifier", "ConfigSection", "ResponseFormat"],
            documentation=cfs_docs,
            mcp_tool="kd_connector_synchronize",
            mcp_skill="kd_ingest",
            rw="write",
        ),
        _cap(
            id="cfs.collect",
            display_name="CFS/Connector Collect",
            category="ingest",
            component="CFS",
            action="Collect",
            required=[],
            optional=["Identifier", "ResponseFormat"],
            documentation=cfs_docs,
            mcp_tool="kd_connector_collect",
            mcp_skill="kd_ingest",
            rw="write",
        ),
        _cap(
            id="cfs.queueinfo",
            display_name="CFS QueueInfo",
            category="ingest",
            component="CFS",
            action="QueueInfo",
            required=[],
            optional=["QueueAction", "QueueName", "Token", "ResponseFormat"],
            documentation="https://cabs.microfocus.com/documentation/idol/IDOL_24_4/WebExConnector_24.4_Documentation/Help/Content/Actions/General/_ACI_QueueInfo.htm",
            mcp_tool="kd_connector_queue_info",
            mcp_skill="kd_ingest",
        ),
    ]

    # ------------------------------------------------------------------
    # File Content Extraction (API-accessible via CFS/NiFi KeyViewFilter, not a standalone HTTP server)
    # ------------------------------------------------------------------
    caps += [
        _cap(
            id="fce.keyview_filter",
            display_name="File Content Extraction via KeyViewFilter (NiFi)",
            category="file_content_extraction",
            component="FileContentExtraction",
            action="KeyViewFilter",
            required=[],
            optional=["processorProperties"],
            documentation=FCE_26_3,
            mcp_tool="kd_fce_describe",
            mcp_skill="kd_file_content_extraction",
            api_type="nifi_processor",
            http_method="N/A",
            port_role="nifi",
            version_notes={
                "26.3": "C2PA metadata extraction; 85 new formats; improved source-code detection; AV1; XrML.",
            },
        ),
    ]

    kg_docs = f"{DOC_PORTAL_26_2}/KnowledgeGraph_26.2_Documentation/Help/Content/Query.htm"
    caps += [
        _cap(
            id="kg.getneighbors",
            display_name="Knowledge Graph GetNeighbors",
            category="knowledge_graph",
            component="KnowledgeGraph",
            action="GetNeighbors",
            required=["SourceNames"],
            optional=["MaxResults", "ResponseFormat"],
            documentation=kg_docs,
            mcp_tool="kd_kg_get_neighbors",
            mcp_skill="kd_knowledge_graph",
        ),
        _cap(
            id="kg.getneighborhood",
            display_name="Knowledge Graph GetNeighborhood",
            category="knowledge_graph",
            component="KnowledgeGraph",
            action="GetNeighborhood",
            required=["SourceNames"],
            optional=["MaxResults", "ResponseFormat"],
            documentation=kg_docs,
            mcp_tool="kd_kg_get_neighborhood",
            mcp_skill="kd_knowledge_graph",
        ),
        _cap(
            id="kg.getcommonneighbors",
            display_name="Knowledge Graph GetCommonNeighbors",
            category="knowledge_graph",
            component="KnowledgeGraph",
            action="GetCommonNeighbors",
            required=["SourceNames"],
            optional=["MaxResults", "ResponseFormat"],
            documentation=kg_docs,
            mcp_tool="kd_kg_get_common_neighbors",
            mcp_skill="kd_knowledge_graph",
        ),
        _cap(
            id="kg.getshortestpath",
            display_name="Knowledge Graph GetShortestPath",
            category="knowledge_graph",
            component="KnowledgeGraph",
            action="GetShortestPath",
            required=["SourceName", "TargetName"],
            optional=["Method", "ResponseFormat"],
            documentation=kg_docs,
            mcp_tool="kd_kg_get_shortest_path",
            mcp_skill="kd_knowledge_graph",
        ),
        _cap(
            id="kg.getsubgraph",
            display_name="Knowledge Graph GetSubgraph",
            category="knowledge_graph",
            component="KnowledgeGraph",
            action="GetSubgraph",
            required=["NodeIDs"],
            optional=["ResponseFormat"],
            documentation=kg_docs,
            mcp_tool="kd_kg_get_subgraph",
            mcp_skill="kd_knowledge_graph",
        ),
        _cap(
            id="kg.suggestlinks",
            display_name="Knowledge Graph SuggestLinks",
            category="knowledge_graph",
            component="KnowledgeGraph",
            action="SuggestLinks",
            required=["NodeName"],
            optional=["ResponseFormat"],
            documentation=kg_docs,
            mcp_tool="kd_kg_suggest_links",
            mcp_skill="kd_knowledge_graph",
        ),
        _cap(
            id="kg.getnodes",
            display_name="Knowledge Graph GetNodes",
            category="knowledge_graph",
            component="KnowledgeGraph",
            action="GetNodes",
            required=[],
            optional=["Sort", "ResponseFormat"],
            documentation=kg_docs,
            mcp_tool="kd_kg_get_nodes",
            mcp_skill="kd_knowledge_graph",
        ),
        _cap(
            id="kg.summarizegraph",
            display_name="Knowledge Graph SummarizeGraph",
            category="knowledge_graph",
            component="KnowledgeGraph",
            action="SummarizeGraph",
            required=[],
            optional=["ResponseFormat"],
            documentation=kg_docs,
            mcp_tool="kd_kg_summarize",
            mcp_skill="kd_knowledge_graph",
        ),
    ]

    answer_docs = f"{DOC_PORTAL_26_2}/AnswerServer_26.2_Documentation/Help/Content/Actions/Management/Parameters/Type.htm"
    caps += [
        _cap(
            id="answer.ask",
            display_name="Answer Server Ask",
            category="question_answering",
            component="AnswerServer",
            action="Ask",
            required=["Text"],
            optional=["SystemName", "CustomizationData", "Timeout", "ResponseFormat"],
            documentation=answer_docs,
            mcp_tool="kd_answer_ask",
            mcp_skill="kd_answer_server",
            version_notes={"26.1": "Ask CustomizationData supports global session data; LLM extractive QA available."},
        ),
        _cap(
            id="answer.getresources",
            display_name="Answer Server GetResources",
            category="question_answering",
            component="AnswerServer",
            action="GetResources",
            required=[],
            optional=["Type", "SystemName", "IDs", "Filter", "ResponseFormat"],
            documentation=answer_docs,
            mcp_tool="kd_answer_get_resources",
            mcp_skill="kd_answer_server",
            version_notes={"26.1": "Type=question_suggestion uses a generative LLM module when configured."},
        ),
        _cap(
            id="answer.converse",
            display_name="Answer Server Converse",
            category="question_answering",
            component="AnswerServer",
            action="Converse",
            required=["Text"],
            optional=["SystemName", "Session", "ResponseFormat"],
            documentation=answer_docs,
            mcp_tool="kd_answer_converse",
            mcp_skill="kd_answer_server",
        ),
        _cap(
            id="answer.getjobstatus",
            display_name="Answer Server GetJobStatus",
            category="question_answering",
            component="AnswerServer",
            action="GetJobStatus",
            required=[],
            optional=["Token", "ResponseFormat"],
            documentation=answer_docs,
            mcp_tool="kd_answer_job_status",
            mcp_skill="kd_answer_server",
        ),
        _cap(
            id="answer.manageresources",
            display_name="Answer Server ManageResources",
            category="question_answering",
            component="AnswerServer",
            action="ManageResources",
            required=["Type"],
            optional=["SystemName", "IDs", "Data", "ResponseFormat"],
            documentation=answer_docs,
            mcp_tool="kd_answer_manage_resources",
            mcp_skill="kd_answer_server",
            rw="write",
        ),
    ]

    face_docs = "https://dlm.microfocus.com/documentation/idol/IDOL_23_3/MediaServer_23.3_Documentation/Help/Content/Actions/Training/_FaceRecognition.htm"
    caps += [
        _cap(
            id="media.trainface",
            display_name="Media TrainFace",
            category="rich_media",
            component="MediaServer",
            action="TrainFace",
            required=[],
            optional=["Identifier", "Database", "ImagePath", "Label", "ResponseFormat"],
            documentation=face_docs,
            mcp_tool="kd_media_train_face",
            mcp_skill="kd_face_analysis",
            rw="write",
        ),
        _cap(
            id="media.listfaces",
            display_name="Media ListFaces",
            category="rich_media",
            component="MediaServer",
            action="ListFaces",
            required=[],
            optional=["Database", "Metadata", "ImageStatus", "ResponseFormat"],
            documentation=face_docs,
            mcp_tool="kd_media_list_faces",
            mcp_skill="kd_face_analysis",
        ),
        _cap(
            id="media.listfacedatabases",
            display_name="Media ListFaceDatabases",
            category="rich_media",
            component="MediaServer",
            action="ListFaceDatabases",
            required=[],
            optional=["ResponseFormat"],
            documentation=face_docs,
            mcp_tool="kd_media_list_face_databases",
            mcp_skill="kd_face_analysis",
        ),
        _cap(
            id="media.removeface",
            display_name="Media RemoveFace",
            category="rich_media",
            component="MediaServer",
            action="RemoveFace",
            required=["Identifier"],
            optional=["Database", "ResponseFormat"],
            documentation="https://www.microfocus.com/documentation/idol/IDOL_24_4/MediaServer_24.4_Documentation/Help/Content/Training/Face_Modify.htm",
            mcp_tool="kd_media_remove_face",
            mcp_skill="kd_face_analysis",
            rw="write",
            destructive=True,
        ),
        _cap(
            id="media.buildface",
            display_name="Media BuildFace",
            category="rich_media",
            component="MediaServer",
            action="BuildFace",
            required=["Identifier"],
            optional=["Database", "ResponseFormat"],
            documentation=face_docs,
            mcp_tool="kd_media_build_face",
            mcp_skill="kd_face_analysis",
            rw="write",
        ),
        _cap(
            id="media.listspeakers",
            display_name="Media ListSpeakers",
            category="rich_media",
            component="MediaServer",
            action="ListSpeakers",
            required=[],
            optional=["Database", "ResponseFormat"],
            documentation=MEDIA_RN_26_2,
            mcp_tool="kd_media_list_speakers",
            mcp_skill="kd_speech_to_text",
            version_notes={"26.2": "ListSpeakers response format changed with the new speaker-ID algorithm."},
        ),
    ]

    caps += [
        _cap(
            id="community.userdecryptsecurityinfo",
            display_name="Community UserDecryptSecurityInfo",
            category="security",
            component="Community",
            action="UserDecryptSecurityInfo",
            required=["SecurityInfo"],
            optional=["ResponseFormat"],
            documentation=SECURITY_26_1,
            mcp_tool="kd_security_decrypt",
            mcp_skill="kd_security",
        ),
        _cap(
            id="community.userdelete",
            display_name="Community UserDelete",
            category="security",
            component="Community",
            action="UserDelete",
            required=["UserName"],
            optional=["ResponseFormat"],
            documentation=SECURITY_26_1,
            mcp_tool="kd_community_user_delete",
            mcp_skill="kd_security",
            rw="write",
            destructive=True,
        ),
        _cap(
            id="ogs.getallusers",
            display_name="OmniGroupServer GetAllUsers",
            category="security",
            component="OmniGroupServer",
            action="GetAllUsers",
            required=[],
            optional=["Repository", "ResponseFormat"],
            documentation=SECURITY_26_1,
            mcp_tool="kd_ogs_get_all_users",
            mcp_skill="kd_security",
        ),
        _cap(
            id="content.getchildren",
            display_name="Content GetChildren",
            category="administration",
            component="Content",
            action="GetChildren",
            required=[],
            optional=["ResponseFormat"],
            documentation=ACI_INTRO_26_2,
            mcp_tool="kd_component_children",
            mcp_skill="kd_administration",
        ),
        _cap(
            id="connectors.catalog",
            display_name="26.3 connector catalog",
            category="ingest",
            component="CFS",
            action="Catalog",
            required=[],
            optional=["name"],
            documentation=DOC_PORTAL_26_3,
            mcp_tool="kd_list_connectors",
            mcp_skill="kd_ingest",
            api_type="documentation_catalog",
            http_method="N/A",
            port_role="nifi",
        ),
    ]

    # ------------------------------------------------------------------
    # NiFi Ingest processors (version-aware; implemented via existing NAR layer)
    # ------------------------------------------------------------------
    for proc, skill in (
        ("PutIDOL", "kd_nifi_ingest"),
        ("GetFileSystem", "kd_nifi_ingest"),
        ("KeyViewFilter", "kd_file_content_extraction"),
        ("Eduction", "kd_entity_extraction"),
        ("GenerateDocumentFlowFile", "kd_nifi_ingest"),
        ("ExecuteDocumentPython", "kd_nifi_ingest"),
        ("RouteDocument", "kd_nifi_ingest"),
    ):
        caps.append(
            _cap(
                id=f"nifi.{proc.lower()}",
                display_name=f"NiFi Ingest {proc}",
                category="nifi",
                component="NiFiIngest",
                action=proc,
                required=[],
                optional=["idolVersion", "nifiVersion"],
                documentation=NIFI_26_3,
                mcp_tool="resolve_idol_nars",
                mcp_skill=skill,
                api_type="nifi_processor",
                http_method="N/A",
                port_role="nifi",
            )
        )

    return caps


SKILLS: list[dict[str, Any]] = [
    {
        "name": "kd_service_discovery",
        "description": "Discover KD components, versions, health, and configured endpoints.",
        "component": "platform",
        "version": "26.3",
        "required_configuration": ["KD_HOST or per-component host/port"],
        "examples": ["What KD components are configured?", "Check Content health on 26.3."],
    },
    {
        "name": "kd_api_discovery",
        "description": "List documented 26.3 APIs and map a natural-language task to an action.",
        "component": "platform",
        "version": "26.3",
        "required_configuration": [],
        "examples": ["What Knowledge Discovery APIs are available in version 26.3?"],
    },
    {
        "name": "idol_content_search",
        "description": "Conceptual, Boolean, fielded, parametric, and natural-language search against Content.",
        "component": "Content",
        "version": "26.3",
        "required_configuration": ["KD_CONTENT_HOST", "KD_CONTENT_PORT or IDOL_HOST/IDOL_PORT"],
        "examples": ["Search Content for contract clauses about indemnity."],
    },
    {
        "name": "idol_content_retrieve",
        "description": "Retrieve document content, metadata, and View renditions.",
        "component": "Content",
        "version": "26.3",
        "required_configuration": ["Content ACI", "optional View ACI"],
        "examples": ["Get document 42 with all fields."],
    },
    {
        "name": "idol_content_similarity",
        "description": "Suggest related documents; 26.3 DAH Suggest supports UseVectors.",
        "component": "Content",
        "version": "26.3",
        "required_configuration": ["Content or DAH ACI"],
        "examples": ["Find documents similar to ID 12 using vectors on 26.3."],
    },
    {
        "name": "idol_content_parametric",
        "description": "Parametric / fielded faceting via GetQueryTagValues and FieldText.",
        "component": "Content",
        "version": "26.3",
        "required_configuration": ["Content ACI"],
        "examples": ["List authors in the Legal database."],
    },
    {
        "name": "idol_content_index",
        "description": "Index, update, and delete Content documents (destructive deletes require confirm).",
        "component": "Content",
        "version": "26.3",
        "required_configuration": ["Content index port"],
        "examples": ["Index this IDX payload into News."],
    },
    {
        "name": "idol_content_admin",
        "description": "Sync, compact, initialize, and manage Content databases.",
        "component": "Content",
        "version": "26.3",
        "required_configuration": ["Content index port"],
        "examples": ["Flush the Content index cache with DRESYNC."],
    },
    {
        "name": "kd_classification",
        "description": "Category suggest/list/train against the Category component + Agentstore.",
        "component": "Category",
        "version": "26.3",
        "required_configuration": ["KD_CATEGORY_HOST"],
        "examples": ["Which category does this policy belong to?"],
    },
    {
        "name": "kd_entity_extraction",
        "description": "Eduction entity and PII extraction, including 26.3 grammar updates.",
        "component": "Eduction",
        "version": "26.3",
        "required_configuration": ["KD_EDUCTION_HOST"],
        "examples": ["Extract PII for Saudi national IDs from this text."],
    },
    {
        "name": "kd_rich_media",
        "description": "Media Server Process/QueueInfo orchestration.",
        "component": "MediaServer",
        "version": "26.3",
        "required_configuration": ["KD_MEDIA_HOST"],
        "examples": ["Process this video with OCR and speech-to-text."],
    },
    {
        "name": "kd_ocr",
        "description": "Media Server OCR including 26.3 language additions.",
        "component": "MediaServer",
        "version": "26.3",
        "required_configuration": ["KD_MEDIA_HOST"],
        "examples": ["OCR this scanned PDF in Armenian."],
    },
    {
        "name": "kd_speech_to_text",
        "description": "Media Server speech-to-text with 26.3 combined Medium/Large model behavior.",
        "component": "MediaServer",
        "version": "26.3",
        "required_configuration": ["KD_MEDIA_HOST"],
        "examples": ["Transcribe this call recording on 26.3."],
    },
    {
        "name": "kd_face_analysis",
        "description": "Face detection/recognition via Media Server Process.",
        "component": "MediaServer",
        "version": "26.3",
        "required_configuration": ["KD_MEDIA_HOST", "Visual channel license"],
        "examples": ["Detect faces in this still image."],
    },
    {
        "name": "kd_object_recognition",
        "description": "Object class recognition and BuildObjectClassRecognizer (restored 26.2+).",
        "component": "MediaServer",
        "version": "26.3",
        "required_configuration": ["KD_MEDIA_HOST"],
        "examples": ["Recognize objects in this warehouse camera frame."],
    },
    {
        "name": "kd_image_description",
        "description": "LLM ImageDescription engine introduced in 26.2 and present in 26.3.",
        "component": "MediaServer",
        "version": "26.3",
        "required_configuration": ["KD_MEDIA_HOST"],
        "examples": ["Describe this image using Media Server ImageDescription."],
    },
    {
        "name": "kd_surveillance",
        "description": "Number plate / vehicle analytics.",
        "component": "MediaServer",
        "version": "26.3",
        "required_configuration": ["KD_MEDIA_HOST", "Surveillance license"],
        "examples": ["Read the number plate in this frame."],
    },
    {
        "name": "kd_file_content_extraction",
        "description": "File Content Extraction 26.3 capabilities exposed through CFS and NiFi KeyViewFilter.",
        "component": "FileContentExtraction",
        "version": "26.3",
        "required_configuration": ["NiFi KeyViewFilter or CFS"],
        "examples": ["Extract C2PA provenance during ingest."],
    },
    {
        "name": "kd_ingest",
        "description": "Connector/CFS synchronize, collect, and queue monitoring.",
        "component": "CFS",
        "version": "26.3",
        "required_configuration": ["KD_CFS_HOST"],
        "examples": ["Start a synchronize on the filesystem connector."],
    },
    {
        "name": "kd_nifi_ingest",
        "description": "Version-aware IDOL NiFi NAR resolution and flow generation (existing NAR layer).",
        "component": "NiFiIngest",
        "version": "26.3",
        "required_configuration": ["IDOL_VERSION", "NIFI_VERSION", "IDOL_NAR_PATH"],
        "examples": ["Generate a 26.3 GetFileSystem → KeyViewFilter → Eduction → PutIDOL flow."],
    },
    {
        "name": "kd_security",
        "description": "SecurityInfo, Community users, query-time security, OTDS 26.3 notes.",
        "component": "Community",
        "version": "26.3",
        "required_configuration": ["KD_COMMUNITY_HOST"],
        "examples": ["Build SecurityInfo for user jane against OTDS."],
    },
    {
        "name": "kd_administration",
        "description": "License, health, configuration inspection, troubleshooting.",
        "component": "platform",
        "version": "26.3",
        "required_configuration": ["component endpoints"],
        "examples": ["Diagnose why Media Server OCR is failing."],
    },
    {
        "name": "kd_query_manipulation",
        "description": "QMS-backed query rewriting and promotions.",
        "component": "QMS",
        "version": "26.3",
        "required_configuration": ["KD_QMS_HOST"],
        "examples": ["Run this query through QMS."],
    },
    {
        "name": "kd_distributed_search",
        "description": "DAH distributed query/suggest including 26.3 UseVectors.",
        "component": "DAH",
        "version": "26.3",
        "required_configuration": ["KD_DAH_HOST"],
        "examples": ["DAH suggest with UseVectors=true on 26.3."],
    },
    {
        "name": "kd_distributed_index",
        "description": "DIH distributed indexing.",
        "component": "DIH",
        "version": "26.3",
        "required_configuration": ["KD_DIH_HOST"],
        "examples": ["Send IDX data through DIH."],
    },
    {
        "name": "kd_community_agents",
        "description": "Agentstore agent/profile/category conceptual matching.",
        "component": "Agentstore",
        "version": "26.3",
        "required_configuration": ["KD_AGENTSTORE_HOST"],
        "examples": ["Find agents similar to this profile text."],
    },
    {
        "name": "kd_knowledge_graph",
        "description": "Knowledge Graph neighbor, path, subgraph, and summary actions documented in 26.2 Help and listed on the 26.3 portal.",
        "component": "KnowledgeGraph",
        "version": "26.3",
        "required_configuration": ["KD_KG_HOST"],
        "examples": ["Get neighbors of Hewlett Packard Enterprise."],
    },
    {
        "name": "kd_answer_server",
        "description": "Answer Server Ask, Converse, GetResources, and job status (LLM question_suggestion from 26.1+).",
        "component": "AnswerServer",
        "version": "26.3",
        "required_configuration": ["KD_ANSWER_HOST"],
        "examples": ["Ask Answer Server: what is the retention period for contracts?"],
    },
]


WORKFLOWS: list[dict[str, Any]] = [
    {"id": "enterprise_document_search", "skill": "kd_workflow_enterprise_search", "steps": ["kd_content_query", "kd_content_get"]},
    {"id": "secure_enterprise_search", "skill": "kd_workflow_secure_search", "steps": ["kd_security_info", "kd_content_query"]},
    {"id": "document_ingestion", "skill": "kd_workflow_ingest", "steps": ["kd_content_index_data", "kd_content_sync"]},
    {"id": "document_enrichment", "skill": "kd_workflow_enrich", "steps": ["kd_educe_text", "kd_category_suggest_from_text"]},
    {"id": "pii_discovery", "skill": "kd_workflow_pii", "steps": ["kd_educe_text"]},
    {"id": "entity_extraction", "skill": "kd_workflow_entities", "steps": ["kd_educe_text"]},
    {"id": "classification", "skill": "kd_workflow_classify", "steps": ["kd_category_suggest_from_text"]},
    {"id": "content_similarity", "skill": "kd_workflow_similar", "steps": ["kd_content_suggest"]},
    {"id": "related_content", "skill": "kd_workflow_related", "steps": ["kd_content_suggest_on_text"]},
    {"id": "investigation", "skill": "kd_workflow_investigate", "steps": ["kd_content_query", "kd_educe_text", "kd_content_suggest"]},
    {"id": "compliance_discovery", "skill": "kd_workflow_compliance", "steps": ["kd_educe_text", "kd_content_query"]},
    {"id": "rich_media_analysis", "skill": "kd_workflow_media", "steps": ["kd_media_process", "kd_media_queue_info"]},
    {"id": "audio_transcription", "skill": "kd_workflow_transcribe", "steps": ["kd_media_speech_to_text"]},
    {"id": "video_analysis", "skill": "kd_workflow_video", "steps": ["kd_media_process"]},
    {"id": "ocr_pipeline", "skill": "kd_workflow_ocr", "steps": ["kd_media_ocr"]},
    {"id": "search_plus_enrichment", "skill": "kd_workflow_search_enrich", "steps": ["kd_content_query", "kd_educe_text"]},
    {"id": "search_plus_summarization", "skill": "kd_workflow_search_summarize", "steps": ["kd_content_query", "kd_content_summarize"]},
    {"id": "search_plus_entities", "skill": "kd_workflow_search_entities", "steps": ["kd_content_query", "kd_educe_text"]},
    {"id": "ingest_plus_classification", "skill": "kd_workflow_ingest_classify", "steps": ["kd_content_index_data", "kd_category_suggest_from_text"]},
    {"id": "ingest_plus_pii", "skill": "kd_workflow_ingest_pii", "steps": ["kd_educe_text", "kd_content_index_data"]},
    {"id": "nifi_ingest_generation", "skill": "kd_workflow_nifi", "steps": ["resolve_idol_nars", "generate_idol_nifi_flow"]},
    {"id": "troubleshooting", "skill": "kd_workflow_troubleshoot", "steps": ["kd_component_health", "kd_component_version"]},
    {"id": "service_health", "skill": "kd_workflow_health", "steps": ["kd_discover_components", "kd_component_health"]},
    {"id": "api_capability_discovery", "skill": "kd_workflow_discover_apis", "steps": ["kd_list_capabilities"]},
    {"id": "version_compatibility", "skill": "kd_workflow_version", "steps": ["kd_resolve_version", "resolve_idol_nars"]},
    {"id": "answer_question", "skill": "kd_workflow_ask", "steps": ["kd_answer_ask"]},
    {"id": "knowledge_graph_explore", "skill": "kd_workflow_graph", "steps": ["kd_kg_get_nodes", "kd_kg_get_neighbors"]},
    {"id": "face_enrollment", "skill": "kd_workflow_face_train", "steps": ["kd_media_train_face", "kd_media_list_faces"]},
]
